# Generated by Django 5.1.6 on 2025-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Not in QuickBooks'), ('paid', 'In QuickBooks'), ('overdue', 'Overdue')], default='unpaid', max_length=20),
        ),
    ]
