# Generated by Django 5.1.6 on 2025-05-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
    ]
