# Generated by Django 5.1.6 on 2025-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
