# Generated by Django 5.1.6 on 2025-05-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorder_entered_in_qb_workorder_invoiced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='entered_in_qb',
        ),
    ]
