# Generated by Django 5.1.6 on 2025-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_remove_workorder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
