# Generated by Django 5.1.6 on 2025-04-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
