# Generated by Django 5.1.6 on 2025-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_alter_workorder_estimated_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
