# Generated by Django 5.1.6 on 2025-03-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_jobattachment_jobnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='phone',
        ),
    ]
