# Generated by Django 5.1.6 on 2025-03-02 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('workorders', '0004_remove_workorder_email_remove_workorder_home_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='clients.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
