# Generated by Django 5.1.6 on 2026-04-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_event_completed_event_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('consult', 'Consult'), ('pickup', 'Pickup'), ('pickup_wrap', 'Pickup and Wrap'), ('wrap', 'Wrap'), ('install', 'Install'), ('deliver_install', 'Deliver and Install'), ('dropoff', 'Drop Off')], max_length=30),
        ),
    ]
