# Generated by Django 5.1.6 on 2026-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Who is scheduled to do this job', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('consult', 'Consult'), ('pickup', 'Pickup'), ('pickup_wrap', 'Pickup and Wrap'), ('wrap', 'Wrap'), ('install', 'Install'), ('deliver_install', 'Deliver and Install'), ('dropoff', 'Drop Off'), ('misc', 'Miscellaneous')], max_length=30),
        ),
    ]
