# Generated by Django 5.1.6 on 2025-03-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_alter_workorder_client_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='pickup_address',
        ),
        migrations.CreateModel(
            name='WorkOrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='workorders.workorder')),
            ],
        ),
    ]
