name: Daily DB Backup

on:
  schedule:
    - cron: "0 4 * * *"  # Midnight ET / 4AM UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout Repo (Required for Actions)
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Trigger Heroku DB Backup
        run: heroku pg:backups:capture --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Download Latest Backup as JSON
        run: |
          BACKUP_URL=$(heroku pg:backups:url --app ${{ secrets.HEROKU_APP_NAME }})
          curl -o full_backup_$(date +%F).json "$BACKUP_URL"
          echo "Downloaded: full_backup_$(date +%F).json"

      - name: Upload Backup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: full_backup_${{ github.run_id }}
          path: full_backup_*.json
